/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AdminAuthRouteImport } from './routes/admin.auth'
import { Route as LpFoilBagRouteImport } from './routes/lp.foil-bag'
import { Route as LpFoilBag2RouteImport } from './routes/lp.foil-bag-2'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminLandingPagesRouteImport } from './routes/_authenticated/admin.landing-pages'
import { Route as AuthenticatedAdminOrdersIndexRouteImport } from './routes/_authenticated/admin.orders.index'
import { Route as AuthenticatedAdminOrdersCreateRouteImport } from './routes/_authenticated/admin.orders.create'
import { Route as AuthenticatedAdminOrdersDeletedRouteImport } from './routes/_authenticated/admin.orders.deleted'
import { Route as AuthenticatedAdminOrdersListRouteImport } from './routes/_authenticated/admin.orders.list'
import { Route as AuthenticatedAdminOrdersWebRouteImport } from './routes/_authenticated/admin.orders.web'
import { Route as AuthenticatedAdminSettingsCourierRouteImport } from './routes/_authenticated/admin.settings.courier'
import { Route as AuthenticatedAdminSettingsTrackingRouteImport } from './routes/_authenticated/admin.settings.tracking'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AdminAuthRoute = AdminAuthRouteImport.update({
  id: '/admin/auth',
  path: '/admin/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LpFoilBagRoute = LpFoilBagRouteImport.update({
  id: '/lp/foil-bag',
  path: '/lp/foil-bag',
  getParentRoute: () => rootRouteImport,
} as any)
const LpFoilBag2Route = LpFoilBag2RouteImport.update({
  id: '/lp/foil-bag-2',
  path: '/lp/foil-bag-2',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminLandingPagesRoute =
  AuthenticatedAdminLandingPagesRouteImport.update({
    id: '/landing-pages',
    path: '/landing-pages',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOrdersIndexRoute =
  AuthenticatedAdminOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOrdersCreateRoute =
  AuthenticatedAdminOrdersCreateRouteImport.update({
    id: '/orders/create',
    path: '/orders/create',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOrdersDeletedRoute =
  AuthenticatedAdminOrdersDeletedRouteImport.update({
    id: '/orders/deleted',
    path: '/orders/deleted',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOrdersListRoute =
  AuthenticatedAdminOrdersListRouteImport.update({
    id: '/orders/list',
    path: '/orders/list',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOrdersWebRoute =
  AuthenticatedAdminOrdersWebRouteImport.update({
    id: '/orders/web',
    path: '/orders/web',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsCourierRoute =
  AuthenticatedAdminSettingsCourierRouteImport.update({
    id: '/settings/courier',
    path: '/settings/courier',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsTrackingRoute =
  AuthenticatedAdminSettingsTrackingRouteImport.update({
    id: '/settings/tracking',
    path: '/settings/tracking',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/thank-you': typeof ThankYouRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/admin/auth': typeof AdminAuthRoute
  '/lp/foil-bag': typeof LpFoilBagRoute
  '/lp/foil-bag-2': typeof LpFoilBag2Route
  '/admin/landing-pages': typeof AuthenticatedAdminLandingPagesRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/orders/create': typeof AuthenticatedAdminOrdersCreateRoute
  '/admin/orders/deleted': typeof AuthenticatedAdminOrdersDeletedRoute
  '/admin/orders/list': typeof AuthenticatedAdminOrdersListRoute
  '/admin/orders/web': typeof AuthenticatedAdminOrdersWebRoute
  '/admin/settings/courier': typeof AuthenticatedAdminSettingsCourierRoute
  '/admin/settings/tracking': typeof AuthenticatedAdminSettingsTrackingRoute
  '/admin/orders/': typeof AuthenticatedAdminOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/thank-you': typeof ThankYouRoute
  '/admin/auth': typeof AdminAuthRoute
  '/lp/foil-bag': typeof LpFoilBagRoute
  '/lp/foil-bag-2': typeof LpFoilBag2Route
  '/admin/landing-pages': typeof AuthenticatedAdminLandingPagesRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/orders/create': typeof AuthenticatedAdminOrdersCreateRoute
  '/admin/orders/deleted': typeof AuthenticatedAdminOrdersDeletedRoute
  '/admin/orders/list': typeof AuthenticatedAdminOrdersListRoute
  '/admin/orders/web': typeof AuthenticatedAdminOrdersWebRoute
  '/admin/settings/courier': typeof AuthenticatedAdminSettingsCourierRoute
  '/admin/settings/tracking': typeof AuthenticatedAdminSettingsTrackingRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/thank-you': typeof ThankYouRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/admin/auth': typeof AdminAuthRoute
  '/lp/foil-bag': typeof LpFoilBagRoute
  '/lp/foil-bag-2': typeof LpFoilBag2Route
  '/_authenticated/admin/landing-pages': typeof AuthenticatedAdminLandingPagesRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/orders/create': typeof AuthenticatedAdminOrdersCreateRoute
  '/_authenticated/admin/orders/deleted': typeof AuthenticatedAdminOrdersDeletedRoute
  '/_authenticated/admin/orders/list': typeof AuthenticatedAdminOrdersListRoute
  '/_authenticated/admin/orders/web': typeof AuthenticatedAdminOrdersWebRoute
  '/_authenticated/admin/settings/courier': typeof AuthenticatedAdminSettingsCourierRoute
  '/_authenticated/admin/settings/tracking': typeof AuthenticatedAdminSettingsTrackingRoute
  '/_authenticated/admin/orders/': typeof AuthenticatedAdminOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/thank-you'
    | '/admin'
    | '/admin/auth'
    | '/lp/foil-bag'
    | '/lp/foil-bag-2'
    | '/admin/landing-pages'
    | '/admin/'
    | '/admin/orders/create'
    | '/admin/orders/deleted'
    | '/admin/orders/list'
    | '/admin/orders/web'
    | '/admin/settings/courier'
    | '/admin/settings/tracking'
    | '/admin/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/thank-you'
    | '/admin/auth'
    | '/lp/foil-bag'
    | '/lp/foil-bag-2'
    | '/admin/landing-pages'
    | '/admin'
    | '/admin/orders/create'
    | '/admin/orders/deleted'
    | '/admin/orders/list'
    | '/admin/orders/web'
    | '/admin/settings/courier'
    | '/admin/settings/tracking'
    | '/admin/orders'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/thank-you'
    | '/_authenticated/admin'
    | '/admin/auth'
    | '/lp/foil-bag'
    | '/lp/foil-bag-2'
    | '/_authenticated/admin/landing-pages'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/orders/create'
    | '/_authenticated/admin/orders/deleted'
    | '/_authenticated/admin/orders/list'
    | '/_authenticated/admin/orders/web'
    | '/_authenticated/admin/settings/courier'
    | '/_authenticated/admin/settings/tracking'
    | '/_authenticated/admin/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ThankYouRoute: typeof ThankYouRoute
  AdminAuthRoute: typeof AdminAuthRoute
  LpFoilBagRoute: typeof LpFoilBagRoute
  LpFoilBag2Route: typeof LpFoilBag2Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/auth': {
      id: '/admin/auth'
      path: '/admin/auth'
      fullPath: '/admin/auth'
      preLoaderRoute: typeof AdminAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lp/foil-bag': {
      id: '/lp/foil-bag'
      path: '/lp/foil-bag'
      fullPath: '/lp/foil-bag'
      preLoaderRoute: typeof LpFoilBagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lp/foil-bag-2': {
      id: '/lp/foil-bag-2'
      path: '/lp/foil-bag-2'
      fullPath: '/lp/foil-bag-2'
      preLoaderRoute: typeof LpFoilBag2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/landing-pages': {
      id: '/_authenticated/admin/landing-pages'
      path: '/landing-pages'
      fullPath: '/admin/landing-pages'
      preLoaderRoute: typeof AuthenticatedAdminLandingPagesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/orders/': {
      id: '/_authenticated/admin/orders/'
      path: '/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AuthenticatedAdminOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/orders/create': {
      id: '/_authenticated/admin/orders/create'
      path: '/orders/create'
      fullPath: '/admin/orders/create'
      preLoaderRoute: typeof AuthenticatedAdminOrdersCreateRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/orders/deleted': {
      id: '/_authenticated/admin/orders/deleted'
      path: '/orders/deleted'
      fullPath: '/admin/orders/deleted'
      preLoaderRoute: typeof AuthenticatedAdminOrdersDeletedRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/orders/list': {
      id: '/_authenticated/admin/orders/list'
      path: '/orders/list'
      fullPath: '/admin/orders/list'
      preLoaderRoute: typeof AuthenticatedAdminOrdersListRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/orders/web': {
      id: '/_authenticated/admin/orders/web'
      path: '/orders/web'
      fullPath: '/admin/orders/web'
      preLoaderRoute: typeof AuthenticatedAdminOrdersWebRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings/courier': {
      id: '/_authenticated/admin/settings/courier'
      path: '/settings/courier'
      fullPath: '/admin/settings/courier'
      preLoaderRoute: typeof AuthenticatedAdminSettingsCourierRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings/tracking': {
      id: '/_authenticated/admin/settings/tracking'
      path: '/settings/tracking'
      fullPath: '/admin/settings/tracking'
      preLoaderRoute: typeof AuthenticatedAdminSettingsTrackingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminLandingPagesRoute: typeof AuthenticatedAdminLandingPagesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminOrdersCreateRoute: typeof AuthenticatedAdminOrdersCreateRoute
  AuthenticatedAdminOrdersDeletedRoute: typeof AuthenticatedAdminOrdersDeletedRoute
  AuthenticatedAdminOrdersListRoute: typeof AuthenticatedAdminOrdersListRoute
  AuthenticatedAdminOrdersWebRoute: typeof AuthenticatedAdminOrdersWebRoute
  AuthenticatedAdminSettingsCourierRoute: typeof AuthenticatedAdminSettingsCourierRoute
  AuthenticatedAdminSettingsTrackingRoute: typeof AuthenticatedAdminSettingsTrackingRoute
  AuthenticatedAdminOrdersIndexRoute: typeof AuthenticatedAdminOrdersIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminLandingPagesRoute: AuthenticatedAdminLandingPagesRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminOrdersCreateRoute: AuthenticatedAdminOrdersCreateRoute,
  AuthenticatedAdminOrdersDeletedRoute: AuthenticatedAdminOrdersDeletedRoute,
  AuthenticatedAdminOrdersListRoute: AuthenticatedAdminOrdersListRoute,
  AuthenticatedAdminOrdersWebRoute: AuthenticatedAdminOrdersWebRoute,
  AuthenticatedAdminSettingsCourierRoute:
    AuthenticatedAdminSettingsCourierRoute,
  AuthenticatedAdminSettingsTrackingRoute:
    AuthenticatedAdminSettingsTrackingRoute,
  AuthenticatedAdminOrdersIndexRoute: AuthenticatedAdminOrdersIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ThankYouRoute: ThankYouRoute,
  AdminAuthRoute: AdminAuthRoute,
  LpFoilBagRoute: LpFoilBagRoute,
  LpFoilBag2Route: LpFoilBag2Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
